config/routes.rb
Rails.application.routes.draw do
  root to: "products#index"
  devise_for :users

  resources :user do
    resources :products
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_properties, dependent: :destroy
  accepts_nested_attributes_for :product_properties, allow_destroy: true

  has_many :properties, through: :product_properties

  belongs_to :user

  validates :name, presence: true, uniqueness: true, length: { maximum: 1024 }

  validates :upc, uniqueness: true, format: { with: /\A\d{12,13}\z|\A\d{10}\z/, message: "length must be 10, 12 or 13"}

  validates :available_on,
                  inclusion: { in: (Date.tomorrow..), message: "must be in future" }
end

app/models/product_property.rb
class ProductProperty < ApplicationRecord
  belongs_to :product
  belongs_to :property
  accepts_nested_attributes_for :property

  validates :value, presence: true, length: { maximum: 255 }
end

app/models/property.rb
class Property < ApplicationRecord
    has_many :product_properties
    has_many :products, through: :product_properties

    validates :name, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!

    def index
        @products = current_user.products.includes(:properties)

        if params[:query].present?
            @products = @products.where("name LIKE ?", "#{params[:query]}%")
        end
    end

    def new
        @product = Product.new
        @product.product_properties.build.build_property
    end

    def create
        @product = current_user.products.new(product_params)

        if @product.save!
            redirect_to root_path, notice: "Success!"
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])

        if @product.update!(product_params)
            redirect_to root_path, notice: "Updated!"
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        Product.find(params[:id]).destroy
        redirect_to root_path
    end

    private
    def product_params
        params.require(:product).permit(:name, :upc, :available_on,
                                    product_properties_attributes: [:id, :value, :_destroy,
                                                            property_attributes: [:id, :name]] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def properties_listing_of product
        prod_value = product.product_properties.pluck(:value)
        prod_name = product.properties.pluck(:name)
        properties = prod_name.zip(prod_value)

        output = ""
        properties.each do | property |
            output << property.join(': ') << ", "
        end
        output.delete_suffix(', ')
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Product Catalogue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'shared/signed_in_navbar' %>
    <% else %>
      <%= render 'shared/signed_out_navbar' %>
    <% end %>

    <div class="container mt-5 mb-5">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_product_property_fields.html.erb
<div class="row mt-1 nested-fields g-3">
    <div class="col-md-5">
        <%= f.fields_for :property do | prop | %>
            <%= prop.text_field :name, class: "form-control", placeholder: "Color"%>
        <% end %>
    </div>

    <div class="col-md-5">
        <%= f.text_field :value, class: "form-control", placeholder: "Red" %>
    </div>

    <div class="col-md-2">
        <%= link_to_remove_association 'Remove', f, class: "btn btn-danger" %>
    </div>
</div>

app/views/products/_products.html.erb
<%= turbo_frame_tag "products" do %>
    <% if @products.present? %>
        <% @products.each do |product| %>
            <p class="mt-5"><span class="fw-bold">Name:</span> <%= product.name %> </p>
            <p class="mt-2"><span class="fw-bold">UPC:</span> <%= product.upc %> </p>
            <p class="mt-2"><span class="fw-bold">Available On:</span> <%= product.available_on.strftime("%d/%m/%Y")  %> </p>
            <p class="mt-2"><span class="fw-bold">Properties:</span> ( <%= properties_listing_of product %> )
            <div >
                <%= link_to "Edit", edit_user_product_path(id: product.id, user_id: current_user.id ) , class: "btn btn-outline-primary" %>
                <%= link_to "Delete", user_product_path(id: product.id, user_id: current_user.id ), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?" }, class: "btn btn-outline-danger" %>
        <% end %>
    <% else %>
        <p>No products!</p>
    <% end %>
<% end %>

app/views/products/edit.html.erb
<h2>Edit Product</h2>

<% if @product.errors.any? %>
    <%= render "shared/validation_errors", model: @product %>
<% end %>

<div class="mt-3">
    <%= render "shared/product_form", path: user_product_path %>
</div>

app/views/products/index.html.erb
<%= form_with(url: root_url, method: :get, data: { turbo_frame: "products" }) do |form|  %>
    <div class="input-group mb-5">
        <%= form.text_field :query, class: "form-control", placeholder: "Search Products" %>
        <%= form.submit "Search",  class: "btn btn-primary" %>
    </div>
<% end %>

<%= render "products", products: @products %>

app/views/products/new.html.erb
<h2>New Product</h2>

<% if @product.errors.any? %>
    <%= render "shared/validation_errors", model: @product %>
<% end %>

<div class="mt-3">

    <%= render "shared/product_form", path: user_products_path %>

</div>

app/views/shared/_product_form.html.erb
<%= form_with model: @product, url: path do | prod | %>
    <%= prod.label :name, class: "form-label mt-3" %>
    <%= prod.text_field :name, autofocus: true, class: "form-control", placeholder: "Xbox"%>


    <%= prod.label :upc, "UPC", class: "form-label mt-3" %>
    <%= prod.text_field :upc, class: "form-control", placeholder: "1234567890" %>

    <%= prod.label :available_on, "Available On", class: "form-label mt-3" %>
    <%= prod.date_field :available_on, class: "form-control" %>

    <h3 class="mt-5">Properties</h3>

    <div class="row g-3">
        <div class="col-md-5 mt-4 fw-bold">
            <span>Property Name</span>
        </div>

        <div class="col-md-5 mt-4 fw-bold">
            <span>Property Value</span>
        </div>

        <div class="col-md-2 mt-4 fw-bold">
            <span>Delete</span>
        </div>
    </div>

    <div class="product_properties">
        <%= prod.fields_for :product_properties do | prod_prop | %>
            <%= render "product_property_fields", f: prod_prop %>
        <% end %>
    </div>

    <div class="mt-4">
        <%= link_to_add_association 'Add More Properties', prod, :product_properties, wrap_object: Proc.new {|quantity| quantity.build_property; quantity },  class: 'btn btn-outline-primary btn-sm' %>
    </div>

    <%= prod.submit  class: 'btn btn-success btn-lg mt-5' %>

<% end %>

app/views/shared/_signed_in_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= image_tag "project_logo.png" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Products", root_path, class:"nav-link active"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Product", new_user_product_path(current_user), class:"nav-link active"  %>
        </li>
      </ul>
      <form class="d-flex">
        <%= link_to "Sign Out", destroy_user_session_path, class:"btn btn-danger", method: :delete  %>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_signed_out_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= image_tag "project_logo.png" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Products", root_path, class:"nav-link disabled"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Product", "#", class:"nav-link disabled"  %>
        </li>
      </ul>
      <form class="d-flex">
        <%= link_to "Sign Up", new_user_registration_path, class:"btn btn-danger"  %>
      </form>
    </div>
  </div>
</nav>

app/views/shared/_validation_errors.html.erb
<div class="alert alert-danger" role="alert">
    <ul>
        <% model.errors.full_messages.each do | message |%>
            <li><%= message %></li>
        <% end %>
    </ul>
</div>